# -*- coding: utf-8 -*-
"""training_mood.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTEtKZwSr2qghScl_cpfb5BtZSJN9dJ0
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

!pip install torch torchvision matplotlib --quiet

from torchvision import datasets, transforms
from torch.utils.data import DataLoader
transform = transforms.Compose([transforms.Grayscale(), transforms.Resize((48,48)), transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

train_data = datasets.ImageFolder('/content/drive/MyDrive/undertone-ai-project/undertone-ai/scripts/train', transform=transform)
test_data = datasets.ImageFolder('/content/drive/MyDrive/undertone-ai-project/undertone-ai/scripts/test', transform=transform)
train_loader=DataLoader(train_data, batch_size=64, shuffle=True)
test_loader=DataLoader(test_data, batch_size=64, shuffle=False)

import torch
import torch.nn as nn
import torch.nn.functional as F

class FER_Model(nn.Module):
    def __init__(self, num_classes=4):
        super(FER_Model, self).__init__()
        self.dropout = nn.Dropout(0.5)
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool  = nn.MaxPool2d(2,2)
        self.fc1   = nn.Linear(128*6*6, 256)
        self.fc2   = nn.Linear(256, num_classes)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        x = F.relu(self.conv2(x))
        x = self.pool(x)
        x = F.relu(self.conv3(x))
        x = self.pool(x)
        x = x.view(-1, 128*6*6)
        x= self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)
        return x

import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = FER_Model().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

fer_mood = {
    0:0,
    1:3,
    2:3,
    3:1,
    4:2,
    5:3,
    6:1
}

epochs = 30
for epoch in range(epochs):
  model.train()
  running_loss = 0
  for images, labels in train_loader:
    images = images.to(device)
    labels = torch.tensor([fer_mood[int(l)] for l in labels]).to(device)

    optimizer.zero_grad()
    outputs = model(images)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  print(f"Epoch {epoch+1}/{epochs} - Loss: {running_loss/len(train_loader):.4f}")

model.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = torch.tensor([fer_mood[int(l)] for l in labels]).to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Test Accuracy: {correct/total*100:.2f}%")

torch.save(model.state_dict(), "fer_model.pth")